<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="LAPTOP-ENMHPA16" failures="2" tests="2" name="Default test(failed)" time="0.051" errors="0" timestamp="01 Apr 2024 03:58:25 GMT">
  <testcase classname="org.Test_rerrun.manual_run" name="tc2" time="0.013">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.Test_rerrun.manual_run.tc2(manual_run.java:13)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase classname="org.Test_rerrun.manual_run" name="tc4" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.Test_rerrun.manual_run.tc4(manual_run.java:21)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc4 -->
  <testcase classname="org.Test_rerrun.manual_run" name="tc5" time="0.0">
    <ignored/>
  </testcase> <!-- tc5 -->
  <testcase classname="org.Test_rerrun.manual_run" name="tc1" time="0.0">
    <ignored/>
  </testcase> <!-- tc1 -->
  <testcase classname="org.Test_rerrun.manual_run" name="tc3" time="0.0">
    <ignored/>
  </testcase> <!-- tc3 -->
</testsuite> <!-- Default test(failed) -->
